#ifndef CPP_CONAN_RELEASE_REUSABLE_WORKFLOW_TEST_CPP_CONAN_RELEASE_REUSABLE_WORKFLOW_TEST_HPP
#define CPP_CONAN_RELEASE_REUSABLE_WORKFLOW_TEST_CPP_CONAN_RELEASE_REUSABLE_WORKFLOW_TEST_HPP

#include <string>

static inline std::string hello() {
    return "Hello world!";
}

inline constexpr char abi_version[] = "0";

#endif //CPP_CONAN_RELEASE_REUSABLE_WORKFLOW_TEST_CPP_CONAN_RELEASE_REUSABLE_WORKFLOW_TEST_HPP
